//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBusinessSense_Task.Models
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Invoices_Items
    {
        [Key, Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        
        [ForeignKey("Invoices")]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Invoice_Id { get; set; }
        public virtual Invoices Invoices { get; set; }
        
        [ForeignKey("Items")]
        [Column(Order = 2)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Item_Id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual Items Items { get; set; }

        [Required]
        public decimal InvItem_SalesPrice { get; set; }

        [Required]
        public decimal Quantity { get; set; }

        [NotMapped]
        public decimal Item_TotalPrice
        {
            get
            {
                return Math.Round(InvItem_SalesPrice * Quantity, 2);
            }
        }

        public bool IsNewInvoiceItem;
    }
}
