//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBusinessSense_Task.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MyDbContext : DbContext
    {
        public MyDbContext() : base(MyFunctions.MyConnection)
        {
            this.Configuration.ProxyCreationEnabled = this.Configuration.LazyLoadingEnabled = true;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.Connection.ConnectionString = MyFunctions.MyConnection;
            Database.SetInitializer<MyDbContext>(null);
            modelBuilder.Entity<Items>();
            modelBuilder.Entity<Invoices>();
            modelBuilder.Entity<Invoices_Items>();
            base.OnModelCreating(modelBuilder);
        }

        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Invoices_Items> Invoices_Items { get; set; }
    }
}
